[project]
name = "cadres-utils-package"
version = "0.1.0"
description = "utility functions for cadres"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.15",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "setuptools>=78.1.0",
]
